name: Air Quality Data Fetch

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Prevents hanging jobs
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        pip install pandas openaq
        
    - name: Make script executable
      run: chmod +x fetch_aqi.py
      
    - name: Run data collection
      run: python fetch_aqi.py
      
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data/latest_aqi.csv
        git diff-index --quiet HEAD || git commit -m "Auto-update AQI data [skip ci]"
        git push
