name: Air Quality Data Fetch

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 3 hours starting from 12 AM
  workflow_dispatch:        # Allows manual triggering

jobs:
  fetch-data:
    runs-on: ubuntu-latest
    timeout-minutes: 5      # Prevents hanging jobs
    permissions:
      contents: write      # Required for pushing changes
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0     # Needed for proper git history
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openaq
        pip install requests 
        
    - name: Verify data directory exists
      run: mkdir -p data
      
    - name: Run data collection
      run: python fetch_aqi.py
      
    - name: Verify CSV was created
      id: verify
      run: |
        if [ ! -f "data/delhi_air_quality_data.csv" ]; then
          echo "File data/delhi_air_quality_data.csv not found!"
          exit 1
        fi
        
    - name: Commit and push changes
      if: steps.verify.outcome == 'success'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatic authentication
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add data/delhi_air_quality_data.csv
        git diff --cached --quiet || {
          git commit -m "Auto-update AQI data [skip ci]"
          git pull --rebase
          git push
        }
